#!/bin/bash

#API endpoint for Pikachu
URL="https://pokeapi.co/api/v2/pokemon/pikachu"

#Output file
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

# Make the API request and save the output
response = $(curl -s -w "%{http_code}" -o "$OUTPUT_FILE" "$URL")

# Check if the request was successful
if [ "$response" -eq 200 ]; then
    echo "[$(date)] Error: Failed to fetch data for Pikachu. Status code: $response" >> "$ERROR_FILE"
    rm -f "$OUTPUT_FILE"
fi